# config.yaml
entreprise:
  nom: "TechFlow Solutions"
  secteur: "Software Development"
  taille: 150
  culture: "Innovation-driven, remote-friendly"
  etape_croissance: "Scale-up"
  defis:
    - "High turnover"
    - "Skill gaps in AI/ML"
    - "Remote team management"
  
  structure_organisationnelle:
    departements:
      - "Engineering"
      - "Sales" 
      - "Marketing"
      - "Human Resources"
      - "Finance"
    niveaux_hierarchiques: 4
    style_management: "Flat hierarchy"
  
  contexte_rh:
    anciennete_moyenne: "2.5 years"
    taux_turnover: "15%"
    budget_formation: "2000€/employee/year"
    cycle_performance: "Annual + quarterly check-ins"
  
  base_de_données:
    chemin: "db"
    nom: "fake_sirh.sqlite"
