# config.yaml
entreprise:
  nom: "Flow Solutions"
  secteur: "Green Energy post AI"
  taille: 150
  culture: "Innovation-driven, remote-friendly"
  etape_croissance: "Scale-up"
  defis:
    - "Shortage of local skilled labor"
    - "High cost of training"
    - "Remote team management"
  
  structure_organisationnelle:
    departements:
      - "R&D"
      - "Wind Power"
      - "Solar Power"
      - "Electrical"
      - "Community Relations"
      - "HR"
      - "Finance"
    niveaux_hierarchiques: 4
    style_management: "Flat hierarchy"
  
  contexte_rh:
    anciennete_moyenne: "2.5 years"
    taux_turnover: "15%"
    budget_formation: "500000 XPF/employee/year"
    cycle_performance: "Annual cycle with quarterly check-ins"
    ratio_hommes: 0.60  # 60% d'hommes, 40% de femmes
  
  technique:
    domaine_email: "flowsolutions.nc"
  
  base_de_données:
    chemin: "db"
    nom: "fake_sirh.sqlite"
