# rag/router_config.yaml

# Modèle d'embedding léger pour la classification sémantique
embedding_model: "sentence-transformers/paraphrase-MiniLM-L3-v2"

# Seuil de confiance (similarité cosinus) pour valider une route
similarity_threshold: 0.68

# Route par défaut si la confiance est trop faible
default_route: "VECTOR"

# Règles de routage basées sur l'intention
rules:
  - name: "Graph Queries - Hiérarchie & Relations"
    destination: "GRAPH"
    intent_examples:
      - "Quel est l'organigramme de l'entreprise ?"
      - "Montre-moi la structure de l'équipe de production."
      - "Qui est le manager de Hugo Durand ?"
      - "A qui rapporte le chef de chantier ?"
      - "Quelles sont les relations entre les employés ?"
      - "Liste les subordonnés de Wesley Robert."
      - "Dessine la hiérarchie du département Support."
      - "Qui est le N+2 de Jonas Martin ?"
      - "Y a-t-il des cycles dans la hiérarchie de management ?"
      - "Montre-moi les employés qui n'ont pas de manager direct."

  - name: "SQL Queries - Agrégats & Comptages"
    destination: "SQL"
    intent_examples:
      - "Combien d'employés travaillent dans l'atelier ?"
      - "Combien d'employés travaillent à la production ?"
      - "Donne-moi la liste de tous les menuisiers poseurs."
      - "Quelle est l'ancienneté moyenne dans l'entreprise ?"
      - "Quel est le nombre total de formations complétées ?"
      - "Quel est le coût moyen des formations de sécurité ?"
      - "Liste les employés ayant un score de performance supérieur à 4."
      - "Quel est le nombre d'employés par département ?"
      - "Donne la liste des personnes embauchées en 2022."
      - "Quel est le taux de turnover ?"
      - "Sors-moi tous les employés dont le nom de famille est 'Martin'."

  - name: "Vector Queries - Recherche Sémantique & Ouverte"
    destination: "VECTOR"
    intent_examples:
      - "Quelle est notre politique sur la sécurité au travail ?"
      - "Fais-moi un résumé du dernier entretien de performance de Nicolas Forest."
      - "Quelles sont les compétences clés de l'équipe de pose ?"
      - "Donne-moi des informations sur le diplôme de Maeva Martin."
      - "Quels sont les principaux défis RH de l'entreprise ?"
      - "Quelles sont les forces et faiblesses de Djina Fabre d'après ses feedbacks ?"
      - "Y a-t-il des formations sur la gestion de projet Agile ?"
      - "Explique-moi la culture de l'entreprise."
      - "Comment se déroule une évaluation annuelle ?"
      - "Trouve le CV de Yohann Ahmat."
